module.exports = {
  names: [
    'Janene Ansell',
    'Gino Zink',
    'Gia Mcwhirt',
    'Keneth Petrick',
    'Deandra Abbott',
    'Fransisca Halley',
    'Suzette Plotkin',
    'An Fernandes',
    'Mia Hines',
    'Karin Argueta',
    'Reina Baisden',
    'Cinthia Chauez',
    'Lianne Chabot',
    'Reba Bryan',
    'Leanne Strauch',
    'Selene Hanke',
    'Sheilah Tea',
    'Gabriel Boyland',
    'Anton Lirette',
    'Josefine Eisenberg',
  ],
}
